#!/bin/bash
#
# chkconfig: 2345 98 8
# description: Teamspeak 3 sunuculari icin otomatik baslatici.

# User kismina dokunmayiniz. "dir" kismini kendi sunucu klasorunuze gore duzenleyiniz:
user=root
dir=/root/ts3/

# Degiskenleri duzenlemenizi tavsiye etmiyorum.
su=/bin/su
ts3=./ts3server_startscript.sh
crack=./AccountingServerEmulator-Linux

case "$1" in
start)
  $su - $user -c "cd $dir;$ts3 start"
  $su - $user -c "cd $dir;$crack"
  ;;
stop)
  $su - $user -c "cd $dir;$ts3 stop"
  $su - $user -c "cd $dir;$crack"
  ;;
restart)
  $su - $user -c "cd $dir;$ts3 restart"
  $su - $user -c "cd $dir;$crack"
  ;;
status)
  $su - $user -c "cd $dir;$ts3 status"
  $su - $user -c "cd $dir;$crack"
  ;;
*)
  echo $"Usage: $0 {start|stop|restart|status}"
  exit 2
esac
exit 0
