#!/bin/bash
#
# chkconfig: 2345 98 8
# description: Teamspeak 3 sunuculari icin otomatik baslatici.

# User kismina dokunmayiniz. "dir" kismini kendi sunucu klasorunuze gore duzenleyiniz:
user=teamspeak
dir=/home/teamspeak/teamspeak3-server_linux_amd64/

# Degiskenleri duzenlemenizi tavsiye etmiyorum.
su=/bin/su
ts3=./ts3server_startscript.sh

case "$1" in
start)
  $su - $user -c "cd $dir;$ts3 start license_accepted=1"
  ;;
stop)
  $su - $user -c "cd $dir;$ts3 stop"
  ;;
restart)
  $su - $user -c "cd $dir;$ts3 restart license_accepted=1"
  ;;
status)
  $su - $user -c "cd $dir;$ts3 status"
  ;;
*)
  echo $"Usage: $0 {start|stop|restart|status}"
  exit 2
esac
exit 0
